Repository Aso2101122/bugbug, pull requests merged in 2022-12, with the labels that each got.

#56 レシピ一覧
  src/main/java/com/example/bugbug/repository/FavoriteRepository.java
  src/main/java/com/example/bugbug/repository/RecipeTagRepository.java
  src/main/java/com/example/bugbug/repository/UserRepository.java
  src/main/java/com/example/bugbug/service/FavoriteService.java
  src/main/java/com/example/bugbug/service/FavoriteServiceImpl.java
  src/main/java/com/example/bugbug/service/RecipeServiceImpl.java
  src/main/java/com/example/bugbug/service/dto/RecipeDto.java
  src/main/resources/static/css/index.css
  src/main/resources/templates/index.html
Labels: Server Side

#55 ログイン・アカウント登録画面
  src/main/resources/static/css/login.css
  src/main/resources/static/css/signup.css
  src/main/resources/static/css/sinup.css
  src/main/resources/static/css/style.css
  src/main/resources/static/js/login.js
  src/main/resources/static/js/main.js
  src/main/resources/templates/header.html
  src/main/resources/templates/login.html
  src/main/resources/templates/question.html
  src/main/resources/templates/sinup.html
Labels: FrontEnd

#59 Feature #26 create password updatepage
  src/main/resources/static/css/passwordCheck.css
  src/main/resources/static/css/passwordUpdate.css
  src/main/resources/templates/passwordCheck.html
  src/main/resources/templates/passwordUpdate.html
Labels: enhancement, fix now

#76 ヘッダー・フッター修正
  src/main/java/com/example/bugbug/controller/IndexController.java
  src/main/resources/static/css/style.css
  src/main/resources/templates/footer.html
  src/main/resources/templates/header.html
  src/main/resources/templates/signup.html
Labels: FrontEnd
